- name: System setup
  hosts: rocky
  become: true
  roles:
    - common
    - podman-rootless
    - zabbix-agent2

- name: User setup
  hosts: rocky
  become: false
  roles:
    - dotfiles
    - zabbix
