- name: System setup
  hosts: rocky
  become: true
  roles:
    - common
    - camera-ap
    - podman-rootless
    - role: tailscale
      tags: tailscale
    - zabbix-agent2

- name: User setup
  hosts: rocky
  become: false
  roles:
    - dotfiles
    - zabbix
    - frigate
