tailscale_repo_url: "https://pkgs.tailscale.com/stable/fedora/tailscale.repo"

tailscale_firewalld_zone: tailscale
tailscale_firewalld_interface: tailscale0
tailscale_firewalld_ports:
  - 5000/tcp
  - 8971/tcp

tailscale_enable_serve: true
tailscale_serve_target: "https+insecure://127.0.0.1:8971"
